apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-admin
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: wiz-admin
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiz-go-app
  template:
    metadata:
      labels:
        app: wiz-go-app
    spec:
      serviceAccountName: wiz-admin
      containers:
        - name: wiz-go-app
          image: jerome.azurecr.io/wiz-go-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: MONGO_URI
            value: "mongodb://admin:adminpass@10.0.1.4:27017/test?authSource=test"


---
apiVersion: v1
kind: Service
metadata:
  name: wiz-go-service
spec:
  selector:
    app: wiz-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

